name: Build Status

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  build-status:
    name: Update Build Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run all checks
        id: checks
        run: |
          echo "Running all checks..."
          LINT_STATUS="passing"
          TYPE_STATUS="passing"
          TEST_STATUS="passing"
          BUILD_STATUS="passing"
          
          bun run lint || LINT_STATUS="failing"
          bun run type-check || TYPE_STATUS="failing"
          bun test || TEST_STATUS="failing"
          bun run build || BUILD_STATUS="failing"
          
          echo "lint=$LINT_STATUS" >> $GITHUB_OUTPUT
          echo "type=$TYPE_STATUS" >> $GITHUB_OUTPUT
          echo "test=$TEST_STATUS" >> $GITHUB_OUTPUT
          echo "build=$BUILD_STATUS" >> $GITHUB_OUTPUT
          
      - name: Update README badges
        run: |
          echo "## Status Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Lint: ${{ steps.checks.outputs.lint }}" >> $GITHUB_STEP_SUMMARY
          echo "- Type Check: ${{ steps.checks.outputs.type }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: ${{ steps.checks.outputs.test }}" >> $GITHUB_STEP_SUMMARY
          echo "- Build: ${{ steps.checks.outputs.build }}" >> $GITHUB_STEP_SUMMARY